version: '3.8'

services:
  eidolon:
    build:
      context: ..
      dockerfile: Dockerfile
    image: eidolon:latest
    container_name: eidolon
    restart: unless-stopped
    volumes:
      # Mount pipelines directory to allow easy pipeline configuration
      - src/pipelines:/app/src/pipelines
      # Mount modules directory to allow adding custom modules
      - src/modules:/app/src/modules
      # Mount settings directory for configuration
      - src/settings:/app/src/settings
    environment:
      - LOG_LEVEL=INFO
    # Default command is "run" which executes the default pipeline
    # Override with: docker-compose run eidolon <command>

  # Example of adding a database service if needed
  # db:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=eidolon
  #   volumes:
  #     - db-data:/var/lib/postgresql/data

# Define volumes for persistent data if needed
volumes:
  db-data:
    driver: local