services:
  eidolon:
    build:
      context: . # Changed context to current directory
      dockerfile: Dockerfile
    image: eidolon:latest
    container_name: eidolon
    restart: unless-stopped
    volumes:
      # Mount pipelines directory to allow easy pipeline configuration
      - ./src/pipelines:/app/src/pipelines
      # Mount modules directory to allow adding custom modules
      - ./src/modules:/app/src/modules
      # Mount settings directory for configuration
      - ./src/settings:/app/src/settings
      # Mount reports directory for output
      - ./reports:/app/reports
    environment: # Add this section
      - PIPELINE_DIR=/app/src/pipelines
      - MODULE_DIR=/app/src/modules
    # Default command is "run" which executes the default pipeline (defined in src/settings/configuration.yaml or default.yaml)
    # Override command: docker-compose run eidolon <command> [options]
    # Example: docker-compose run eidolon run --pipeline aethon
    # Example: docker-compose run eidolon list modules

# Removed commented-out db service and volumes for clarity
# Define volumes for persistent data if needed (e.g., for specific module data)
# volumes:
#   module-data:
#     driver: local