registry:
  url: 'https://github.com/lachlanharrisdev/PROJECT-EIDOLON/releases/download/{tag}'
  name: ''
  repository: ''
  tag: 'latest'
logging:
  level: 'DEBUG'
  format: '%(asctime)s: %(levelname)s from %(name)s - %(message)s [%(filename)s:%(lineno)d]'
  file_level: 'DEBUG'
  console_level: 'INFO'

