registry:
  url: 'https://github.com/lachlanharrisdev/PROJECT-EIDOLON/releases/download/{tag}'
  name: ''
  repository: ''
  tag: 'latest'
logging:
  # Setting the log level: CRITICAL, ERROR, WARNING, INFO, DEBUG
  level: 'INFO'
modules:
  directory: 'modules'
  log_level: 'INFO'

