pipeline:
  name: aethon 
  description: >
    Lightweight, high-performance web crawler with console reporting

  execution:
    timeout: 600s
    max_threads: 8

  modules:
    - id: crawler
      name: aethon_crawler
      config:
        url: "https://www.eddyconsulting.com.au/"
        level: 2
        threads: 8
        delay: 1
        timeout: 10
        exclude: "logout|sign-out"
        wayback: false
        keys: false  # Simplified - we're focusing on core crawler functionality
        ninja: false
        dns: true
      outputs:
        - crawled_urls: "crawled_urls"
        - extracted_data: "extracted_data" 
        - crawl_status: "crawl_status"
      run_mode: loop  # or once, on_trigger