pipeline:
  name: aethon 
  description: >
    Advanced web crawler and report generator pipeline based on Aethon

  execution:
    timeout: 600s
    retries: 2 
    error_policy: halt  # or continue, isolate, log_only
    max_threads: 8

  modules:
    - id: crawler # how this module is identified within the pipeline
      module: aethon_crawler # the name of the actual module used
      config: # custom configuration that could be given to the module
        url: "https://youtube.com"
        level: 2
        threads: 8
        delay: 1
        timeout: 10
        exclude: "logout|sign-out"
        wayback: false
        keys: true
        ninja: false
        dns: true
      outputs: # map the name of the outputs located in the module's `module.yaml` file to an output usable by other modules in the pipeline
        - crawled_urls: "crawled_urls"
        - extracted_data: "extracted_data"
        - parameters: "parameters"
        - intel: "intel"
        - secret_keys: "secret_keys"
        - js_files: "js_files"
        - subdomains: "subdomains"
        - crawl_status: "crawl_status"
      run_mode: loop  # or once, on_trigger
      
    - id: reporter
      module: aethon_report
      depends_on:
        - crawler
      config:
        format: "html"  # html, md, json, or txt
        output_dir: "reports"
        filename: null  # auto-generated if null
        include_sections:  # sections to include in the report
          - summary
          - urls
          - parameters
          - emails
          - social
          - secrets
          - files
          - js
          - subdomains
        auto_generate: true
        theme: "default"
      inputs:
        crawled_urls: crawler.crawled_urls
        extracted_data: crawler.extracted_data
        parameters: crawler.parameters
        intel: crawler.intel
        secret_keys: crawler.secret_keys
        js_files: crawler.js_files
        subdomains: crawler.subdomains
        crawl_status: crawler.crawl_status
      outputs:
        - report_path: "report_path"
        - report_summary: "report_summary"
        - completion_status: "completion_status"
      run_mode: loop