pipeline:
  name: aethon 
  description: >
    Lightweight, high-performance web crawler with console reporting

  execution:
    timeout: 600s
    max_threads: 8

  modules:
  - name: aethon_urllist
    id: loader
    config:
      supported_formats: [".txt", ".csv", ".json", ".xml"]
      example_mode: true
      example_count: 30
      skip_empty_lines: true
      strip_whitespace: true
      remove_duplicates: true
    outputs:
    - urls: "urls"
    run_mode: once

  - name: aethon_urlclean
    id: cleaner
    config:
      whitelist: []
      blacklist: ["css", "png", "jpg", "jpeg", "svg"]
      filters: ["removecontent", "noparams"]
      keepslash: true
    input:
      urls: loader.urls
    outputs:
    - cleaned_urls: "cleaned_urls"
    - url_count: "url_count"
    run_mode: reactive
    depends_on: [loader]

  - name: aethon_crawler
    id: crawler
    config:
      concurrency: 300
      timeout: 8
      user_agent: "Eidolon/1.0 Web Crawler"
      follow_redirects: true
      max_redirects: 5
      retry_count: 3
      retry_delay: 1
      verify_ssl: true
    input:
      urls: cleaner.cleaned_urls
    outputs:
    - crawled_data: "crawled_data"
    - crawl_count: "crawl_count"
    run_mode: reactive
    depends_on: [cleaner]