name: default
modules:
  - name: keyword_monitor
  - name: template_module
    depends_on:
      - keyword_monitor
    input_mappings:
      keywords: keywords
  - name: keyword_printer
    depends_on:
      - template_module
    input_mappings:
      keywords: processed_keywords