name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-asyncio
        python -m spacy download en_core_web_sm

    - name: Run Core Tests
      run: |
        pytest tests/ --log-cli-level=INFO
    
    - name: Run Plugin Tests
      run: |
        pytest default-plugins/ --log-cli-level=INFO --tb=short --disable-warnings -p no:warnings
        pytest plugins/ --log-cli-level=INFO --tb=short --disable-warnings -p no:warnings
        
    - name: Upload Keyword Monitor Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: keyword-monitor-results
        path: data/tests/keyword_monitor_results.json