name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-asyncio pytest-mock
        python -m spacy download en_core_web_sm
    
    - name: Run Tests
      run: |
        pytest 

    - name: Generate Signed Module Hashes
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        python core/security/generate_module_hashes.py
    
    - name: Upload Verified Modules
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: verified-module-hashes
        path: settings/verified_modules.json