name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies and application
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install spacy pytest-asyncio pytest-mock
        python -m build
        pip install dist/*.tar.gz
        python -m spacy download en_core_web_sm

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Verify CLI functionality
      run: |
        eidolon --help

    - name: Run Tests
      run: |
        pytest
    
    - name: Generate Signed Module Hashes
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        python src/core/security/generate_module_hashes.py
    
    - name: Upload Verified Modules
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: verified-module-hashes
        path: src/settings/verified_modules.json