name: Module Hash Verification

on:
  push:
    branches:
      - main
    paths:
      - 'src/modules/**'

permissions:
  contents: write

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
         python -m pip install --upgrade pip
         pip install build
         pip install PyYAML cryptography

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Generate Verified Module Hashes
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          python src/core/security/generate_module_hashes.py

      - name: Commit and Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b update-verified-modules
          git add src/settings/verified_modules.json
          git commit -m "Update verified_modules.json [skip ci]" || echo "No changes to commit"
          git push origin update-verified-modules || echo "Branch already exists"
          gh pr create --title "Update verified_modules.json" --body "Automated update of verified module hashes" --head update-verified-modules --base main
