name: 'Sample Plugin'
alias: 'sample-plugin'
creator: 'John Doe'
runtime:
  main: 'main.py'
  tests:
    - 'tests/core.py'
repository: 'https://github.com/lachlanharrisdev/PROJECT-EIDOLON'
description: 'This is a sample plugin description'
version: '0.0.1'
requirements:
  - name: 'PyYAML'
    version: '6.0.2'